In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
import seaborn as sns
import os.path as path
import os
import matplotlib
import matplotlib.font_manager
import matplotlib.pyplot as plt # graphs plotting
from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline
import numpy
import csv 

from matplotlib import rc

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import classification_report, confusion_matrix 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold 
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean


from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score

import statistics

from sklearn.cluster import KMeans

from sklearn.datasets import load_digits
from sklearn.decomposition import KernelPCA

import math
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import confusion_matrix

# for Arial typefont
matplotlib.rcParams['font.family'] = 'Arial'


## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("Packages imported")

Packages imported


In [2]:
# https://data.cdc.gov/Case-Surveillance/COVID-19-Case-Surveillance-Public-Use-Data-with-Ge/n8mc-b4w4/data

read_path = "C:/Users/sali85/Desktop/COVID-19_Case_Surveillance_Public_Use_Data_with_Geography.csv"

dataset_full = []
# host_names_ne = []

with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        tmp = row
        dataset_full.append(tmp)
    


In [3]:
len(dataset_full)

29851451

In [6]:
aa = dataset_full[1]

In [7]:
aa

['2021-07',
 'VT',
 '50',
 'WASHINGTON',
 '48477',
 'NA',
 'NA',
 'NA',
 'NA',
 '0',
 '',
 'Missing',
 'Yes',
 'Laboratory-confirmed case',
 'Asymptomatic',
 'No',
 'Missing',
 'No',
 '']

In [16]:
if(aa[5]=='NA' and aa[0]!='NA'):
    print("True")

True


In [17]:
dataset_reduced = []
for i in range(1,len(dataset_full)):
    tmp = dataset_full[i]
    if tmp[0]!="NA" and tmp[1]!="NA" and tmp[2]!="NA" and tmp[3]!="NA" and tmp[4]!="NA" and tmp[5]!="NA" and tmp[6]!="NA" and tmp[7]!="NA" and tmp[8]!="NA" and tmp[9]!="NA" and tmp[10]!="NA" and tmp[11]!="NA" and tmp[12]!="NA" and tmp[13]!="NA" and tmp[14]!="NA" and tmp[15]!="NA" and tmp[16]!="NA" and tmp[17]!="NA" and tmp[18]!="NA":
        if tmp[0]!="" and tmp[1]!="" and tmp[2]!="" and tmp[3]!="" and tmp[4]!="" and tmp[5]!="" and tmp[6]!="" and tmp[7]!="" and tmp[8]!="" and tmp[9]!="" and tmp[10]!="" and tmp[11]!="" and tmp[12]!="" and tmp[13]!="" and tmp[14]!="" and tmp[15]!="" and tmp[16]!="" and tmp[17]!="" and tmp[18]!="":
            dataset_reduced.append(tmp)
        
        
        
        

In [18]:
len(dataset_reduced)

737864

In [19]:
dataset_reduced_2 = []
for i in range(1,len(dataset_reduced)):
    tmp = dataset_reduced[i]
    if tmp[0]!="Missing" and tmp[1]!="Missing" and tmp[2]!="Missing" and tmp[3]!="Missing" and tmp[4]!="Missing" and tmp[5]!="Missing" and tmp[6]!="Missing" and tmp[7]!="Missing" and tmp[8]!="Missing" and tmp[9]!="Missing" and tmp[10]!="Missing" and tmp[11]!="Missing" and tmp[12]!="Missing" and tmp[13]!="Missing" and tmp[14]!="Missing" and tmp[15]!="Missing" and tmp[16]!="Missing" and tmp[17]!="Missing" and tmp[18]!="Missing":
        dataset_reduced_2.append(tmp)

In [20]:
len(dataset_reduced_2)

95984

In [22]:
arr_data = np.array(dataset_reduced_2)

In [ ]:
np.save("E:\RA\Death Classification\Dataset/CDC_Data.npy",arr_data)

# Loading Data

In [2]:
covid_data = np.load("E:\RA\Death Classification\Dataset/CDC_Data.npy")

In [3]:
len(covid_data)

95984

In [18]:
aa = []
for i in range(len(covid_data)):
    tmp = covid_data[i]
    aa.append(tmp[1])

In [22]:
unq = list(np.unique(aa))
len(unq)

16

In [23]:
# unq.index("ASHTABULA")

aaa = []
for i in range(len(covid_data)):
    tmp = unq.index(aa[i])
    aaa.append(tmp)

In [24]:
len(np.unique(aaa))

16

In [25]:
print("Writting Frequency Vectors")   
write_path_11 = "E:/RA/Death Classification/Dataset/tmp.csv"

with open(write_path_11, 'w', newline='') as file:
    writer = csv.writer(file)
    for ij in range(0,len(aaa)):
        ccv = aaa[ij]
        writer.writerow([ccv])


Writting Frequency Vectors


# Classification Code Starts From Here

In [9]:
read_path = "E:/RA/Death Classification/Dataset/CDC_Data_int_converted - Copy.csv"
dataset_final = []

with open(read_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        tmp = row
        dataset_final.append(tmp)

In [3]:
len(dataset_final),len(dataset_final[0])

(95984, 20)

In [10]:
labels = []
attributes = []
for i in range(0,len(dataset_final)):
    tmp = dataset_final[i]
    tmp_2 = tmp[0:19]
    tmp_arr = []
    for j in range(0,len(tmp_2)):
        tmp_arr.append(int(tmp_2[j]))
    attributes.append(tmp_arr)
    labels.append(tmp[19])
    
    

In [11]:
labels_int = []

for i in range(0,len(labels)):
    if labels[i]=="Yes":
        labels_int.append(1)
    elif labels[i]=="No":
        labels_int.append(2)
    else:
        labels_int.append(0)

# Classification Functions

In [12]:
# In[4]
def roc_auc_score_multiclass(actual_class, pred_class, average = "macro"):

    unique_class = set(actual_class)
    roc_auc_dict = {}
    for per_class in unique_class:
        #creating a list of all the classes except the current class 
        other_class = [x for x in unique_class if x != per_class]

        #marking the current class as 1 and all other classes as 0
        new_actual_class = [0 if x in other_class else 1 for x in actual_class]
        new_pred_class = [0 if x in other_class else 1 for x in pred_class]

        #using the sklearn metrics method to calculate the roc_auc_score
        roc_auc = roc_auc_score(new_actual_class, new_pred_class, average = average)
        roc_auc_dict[per_class] = roc_auc
    
    
    check = pd.DataFrame(roc_auc_dict.items())
    return mean(check)

def svm_fun_kernel(X_train,y_train,X_test,y_test,kernel_mat):

#     clf = svm.SVC()
    clf = svm.SVC(kernel=kernel_mat)
    
    #Train the model using the training sets
    clf.fit(kernel_mat, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Kernel Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    
# In[5]
##########################  SVM Classifier  ################################
def svm_fun(X_train,y_train,X_test,y_test):
    #Create a svm Classifier
    clf = svm.SVC(kernel='linear') # Linear Kernel

    #Train the model using the training sets
    clf.fit(X_train, y_train)

    #Predict the response for test dataset
    y_pred = clf.predict(X_test)
    
    svm_acc = metrics.accuracy_score(y_test, y_pred)
#     print("SVM Accuracy:",svm_acc)
    
    svm_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("SVM Precision:",svm_prec)
    
    svm_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("SVM Recall:",svm_recall)

    svm_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("SVM F1 Weighted:",svm_f1_weighted)
    
    svm_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("SVM F1 macro:",svm_f1_macro)
    
    svm_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("SVM F1 micro:",svm_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix SVM : \n", confuse)
    print("SVM Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
#    print(macro_roc_auc_ovo[1])
    check = [svm_acc,svm_prec,svm_recall,svm_f1_weighted,svm_f1_macro,svm_f1_micro,macro_roc_auc_ovo[1]]
    return(check)
    


# In[5]
##########################  NB Classifier  ################################
def gaus_nb_fun(X_train,y_train,X_test,y_test):
    gnb = GaussianNB()
    y_pred = gnb.fit(X_train, y_train).predict(X_test)


    NB_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Gaussian NB Accuracy:",NB_acc)

    NB_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Precision:",NB_prec)
    
    NB_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB Recall:",NB_recall)
    
    NB_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Gaussian NB F1 weighted:",NB_f1_weighted)
    
    NB_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Gaussian NB F1 macro:",NB_f1_macro)
    
    NB_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Gaussian NB F1 micro:",NB_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix NB : \n", confuse)
    print("NB Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    check = [NB_acc,NB_prec,NB_recall,NB_f1_weighted,NB_f1_macro,NB_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  MLP Classifier  ################################
def mlp_fun(X_train,y_train,X_test,y_test):
    # Feature scaling
    scaler = StandardScaler()  
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)  
    X_test_2 = scaler.transform(X_test)


    # Finally for the MLP- Multilayer Perceptron
    mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
    mlp.fit(X_train, y_train)


    y_pred = mlp.predict(X_test_2)
    
    MLP_acc = metrics.accuracy_score(y_test, y_pred)
#     print("MLP Accuracy:",MLP_acc)
    
    MLP_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("MLP Precision:",MLP_prec)
    
    MLP_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("MLP Recall:",MLP_recall)
    
    MLP_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("MLP F1:",MLP_f1_weighted)
    
    MLP_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("MLP F1:",MLP_f1_macro)
    
    MLP_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("MLP F1:",MLP_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix MLP : \n", confuse)
    print("MLP Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [MLP_acc,MLP_prec,MLP_recall,MLP_f1_weighted,MLP_f1_macro,MLP_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  knn Classifier  ################################
def knn_fun(X_train,y_train,X_test,y_test):
    classifier = KNeighborsClassifier(n_neighbors=5)
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    knn_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Knn Accuracy:",knn_acc)
    
    knn_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Knn Precision:",knn_prec)
    
    knn_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Knn Recall:",knn_recall)
    
    knn_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Knn F1 weighted:",knn_f1_weighted)
    
    knn_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Knn F1 macro:",knn_f1_macro)
    
    knn_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Knn F1 micro:",knn_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix KNN : \n", confuse)
    print("KNN Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [knn_acc,knn_prec,knn_recall,knn_f1_weighted,knn_f1_macro,knn_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
##########################  Random Forest Classifier  ################################
def rf_fun(X_train,y_train,X_test,y_test):
    # Import the model we are using
    from sklearn.ensemble import RandomForestClassifier
    # Instantiate model with 1000 decision trees
    rf = RandomForestClassifier(n_estimators = 100)
    # Train the model on training data
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)

    fr_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Random Forest Accuracy:",fr_acc)
    
    fr_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Random Forest Precision:",fr_prec)
    
    fr_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Random Forest Recall:",fr_recall)
    
    fr_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Random Forest F1 weighted:",fr_f1_weighted)
    
    fr_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Random Forest F1 macro:",fr_f1_macro)
    
    fr_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Random Forest F1 micro:",fr_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix RF : \n", confuse)
    print("RF Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [fr_acc,fr_prec,fr_recall,fr_f1_weighted,fr_f1_macro,fr_f1_micro,macro_roc_auc_ovo[1]]
    return(check)

# In[5]
    ##########################  Logistic Regression Classifier  ################################
def lr_fun(X_train,y_train,X_test,y_test):

    model = LogisticRegression(solver='liblinear', random_state=0)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    LR_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    LR_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    LR_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    LR_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    LR_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    LR_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix LR : \n", confuse)
    print("LR Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [LR_acc,LR_prec,LR_recall,LR_f1_weighted,LR_f1_macro,LR_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


def fun_decision_tree(X_train,y_train,X_test,y_test):
    from sklearn import tree
    
    clf = tree.DecisionTreeClassifier()    
    clf = clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    dt_acc = metrics.accuracy_score(y_test, y_pred)
#     print("Logistic Regression Accuracy:",LR_acc)
    
    dt_prec = metrics.precision_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Precision:",LR_prec)
    
    dt_recall = metrics.recall_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression Recall:",LR_recall)
    
    dt_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
#     print("Logistic Regression F1 weighted:",LR_f1_weighted)
    
    dt_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
#     print("Logistic Regression F1 macro:",LR_f1_macro)
    
    dt_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
#     print("Logistic Regression F1 micro:",LR_f1_micro)
    
    confuse = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix DT : \n", confuse)
    print("DT Class Wise Accuracy : ",confuse.diagonal()/confuse.sum(axis=1))
    ######################## Compute ROC curve and ROC area for each class ################
    y_prob = y_pred
    macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')
    
    check = [dt_acc,dt_prec,dt_recall,dt_f1_weighted,dt_f1_macro,dt_f1_micro,macro_roc_auc_ovo[1]]
    return(check)


In [13]:
X = np.array(attributes)
y =  np.array(labels_int)

X_orig = np.array(attributes)

counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []


from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=1, test_size=0.3)
sss.get_n_splits(X, y)
train_index, test_index = next(sss.split(X, y)) 

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [10]:
X_train.shape,X_test.shape

((67188, 19), (28796, 19))

In [11]:
a = (X_test[0])
# for i in range(0,len(a)):
#     print((a[i]))

In [ ]:
import timeit

start = timeit.default_timer()
gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("NB Time : ", stop - start) 

start = timeit.default_timer()
mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("MLP Time : ", stop - start) 

start = timeit.default_timer()
knn_return = knn_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("KNN Time : ", stop - start) 

start = timeit.default_timer()
rf_return = rf_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("RF Time : ", stop - start) 

start = timeit.default_timer()
lr_return = lr_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("LR Time : ", stop - start) 

start = timeit.default_timer()
dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("DT Time : ", stop - start) 

start = timeit.default_timer()
svm_return = svm_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("SVM Time : ", stop - start) 

gauu_nb_table.append(gauu_nb_return)
mlp_table.append(mlp_return)
knn_table.append(knn_return)
rf_table.append(rf_return)
lr_table.append(lr_return)
dt_table.append(dt_return)
svm_table.append(svm_return)
     
svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


Confusion Matrix NB : 
 [[ 1397    20   174]
 [   57   195   114]
 [ 4842   698 21299]]
NB Class Wise Accuracy :  [0.87806411 0.53278689 0.79358396]
NB Time :  0.18693579999990106
Confusion Matrix MLP : 
 [[ 1107     0   484]
 [   11    54   301]
 [  889    44 25906]]
MLP Class Wise Accuracy :  [0.69578881 0.14754098 0.96523715]
MLP Time :  38.59970339999995
Confusion Matrix KNN : 
 [[  855     3   733]
 [   10    81   275]
 [  535   106 26198]]
KNN Class Wise Accuracy :  [0.53739786 0.22131148 0.97611684]
KNN Time :  4.322970899999973
Confusion Matrix RF : 
 [[  867     2   722]
 [    8   103   255]
 [  456   121 26262]]
RF Class Wise Accuracy :  [0.54494029 0.28142077 0.97850143]
RF Time :  4.862974000000122


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix LR : 
 [[    0     0  1591]
 [    0     0   366]
 [    0     0 26839]]
LR Class Wise Accuracy :  [0. 0. 1.]
LR Time :  0.900952899999993
Confusion Matrix DT : 
 [[  967     5   619]
 [   13   115   238]
 [  683   247 25909]]
DT Class Wise Accuracy :  [0.60779384 0.31420765 0.96534893]
DT Time :  0.34448429999997643


In [13]:
#taking average of all k-fold performance values
final_mean_mat = []

final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["SVM","NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
SVM  0.931796   0.916067  0.931796       0.922241    0.463193    0.931796   
NB   0.786186   0.934514  0.786186       0.837678    0.493988    0.786186   
MLP  0.941554   0.932419  0.941554       0.935072    0.594290    0.941554   
KNN  0.943951   0.937328  0.943951       0.939806    0.606581    0.943951   
RF   0.945617   0.940163  0.945617       0.942239    0.640707    0.945617   
LR   0.933150   0.870770  0.933150       0.900882    0.321806    0.933150   
DT   0.936727   0.937597  0.936727       0.937114    0.624576    0.936727   

      ROC AUC  
SVM  0.603208  
NB   0.802115  
MLP  0.664920  
KNN  0.691581  
RF   0.712880  
LR   0.500000  
DT   0.733119

# Boruta for Feature Selection

In [8]:
### make X_shadow by randomly permuting each column of X
X_df = pd.DataFrame(X)
X_df.columns = ["c1","c2","c3","c4","c5","c6","c7","c8","c9","c10","c11","c12","c13","c14","c15","c16","c17","c18","c19"]
X_df

c1  c2  c3  c4   c5     c6  c7  c8  c9  c10  c11  c12  c13  c14  c15  \
0      2020   4   6  20   63  20057   2   1   0    1    0    0    0    0    1   
1      2020   7   6  20  180  20209   2   2   0    1    0    0    3    1    1   
2      2020  11   6  20   75  20079   2   1   6    1    1    0    4    1    2   
3      2020   8   6  20  102  20111   2   2   6    1    0    0    2    1    1   
4      2020   7   6  20  140  20169   2   1   6    1    0    0    0    0    1   
...     ...  ..  ..  ..  ...    ...  ..  ..  ..  ...  ...  ...  ...  ...  ...   
95979  2020   9  11  32   35  32003   3   1   6    0    0    0    2    1    1   
95980  2020   9  11  32   35  32003   3   1   6    0    0    0    4    1    1   
95981  2020   9  11  32   35  32003   3   1   6    0    0    0    4    1    1   
95982  2020   9  11  32   35  32003   3   1   6    0    0    0    2    1    1   
95983  2020   9  11  32   35  32003   3   1   6    0    0    0    2    1    1   

       c16  c17  c18  c19  
0        1    2    2    1  
1        1    2    2    2  
2        1    2    2    2  
3        1    2    2    2  
4        1    2    0    1  
...    ...  ...  ...  ...  
95979    1    2    2    1  
95980    1    2    2    1  
95981    1    2    2    1  
95982    1    2    2    1  
95983    1    2    2    1  

[95984 rows x 19 columns]

In [9]:
np.random.seed(42)
X_shadow = X_df.apply(np.random.permutation)
X_shadow.columns = ['shadow_' + feat for feat in X_df.columns]
### make X_boruta by appending X_shadow to X
X_boruta = pd.concat([X_df, X_shadow], axis = 1)

In [25]:
len(X_boruta)

95984

In [30]:
(X_boruta)

...  shadow_  shadow_  \
0      2020   4   6  20   63  20057  2  1  0  1  ...        2        0   
1      2020   7   6  20  180  20209  2  2  0  1  ...        2        0   
2      2020  11   6  20   75  20079  2  1  6  1  ...        2        0   
3      2020   8   6  20  102  20111  2  2  6  1  ...        2        0   
4      2020   7   6  20  140  20169  2  1  6  1  ...        2        1   
...     ...  ..  ..  ..  ...    ... .. .. .. ..  ...      ...      ...   
95979  2020   9  11  32   35  32003  3  1  6  0  ...        2        1   
95980  2020   9  11  32   35  32003  3  1  6  0  ...        2        0   
95981  2020   9  11  32   35  32003  3  1  6  0  ...        2        0   
95982  2020   9  11  32   35  32003  3  1  6  0  ...        2        1   
95983  2020   9  11  32   35  32003  3  1  6  0  ...        2        0   

       shadow_  shadow_  shadow_  shadow_  shadow_  shadow_  shadow_  shadow_  
0            0        1        1        1        1        2        2        1  
1            0        4        1        1        1        2        2        1  
2            0        4        1        2        1        2        2        1  
3            0        4        1        1        1        2        2        2  
4            0        1        1        1        1        2        0        1  
...        ...      ...      ...      ...      ...      ...      ...      ...  
95979        0        0        1        1        1        2        2        1  
95980        0        2        1        1        1        2        2        1  
95981        0        3        1        1        1        2        2        1  
95982        0        1        1        1        1        2        2        1  
95983        0        0        1        1        1        2        2        1  

[95984 rows x 38 columns]

In [10]:
from sklearn.ensemble import RandomForestRegressor
### fit a random forest (suggested max_depth between 3 and 7)
forest = RandomForestRegressor(max_depth = 5, random_state = 42)
forest.fit(X_boruta, y)
### store feature importances
feat_imp_X = forest.feature_importances_[:len(X_df.columns)]
feat_imp_shadow = forest.feature_importances_[len(X_df.columns):]
### compute hits
hits = feat_imp_X > feat_imp_shadow.max()

In [11]:
hits

array([False,  True,  True,  True,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False,  True,  True,
        True])

In [12]:
indices_tmp = []

for i in range(len(hits)):
    if(hits[i]==True):
        indices_tmp.append(i)

In [13]:
(indices_tmp)

[1, 2, 3, 4, 5, 6, 9, 12, 16, 17, 18]

In [14]:
final_boruta_data = np.array(X_df.iloc[:,indices_tmp])

In [15]:
X = final_boruta_data
y =  np.array(labels_int)


counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []


from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=1, test_size=0.3)
sss.get_n_splits(X, y)
train_index, test_index = next(sss.split(X, y)) 

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [16]:
X_train.shape,X_test.shape

((67188, 11), (28796, 11))

In [1]:
X_train[0]

NameError: name 'X_train' is not defined

In [16]:
import timeit

start = timeit.default_timer()
gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("NB Time : ", stop - start) 

start = timeit.default_timer()
mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("MLP Time : ", stop - start) 

start = timeit.default_timer()
knn_return = knn_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("KNN Time : ", stop - start) 

start = timeit.default_timer()
rf_return = rf_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("RF Time : ", stop - start) 

start = timeit.default_timer()
lr_return = lr_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("LR Time : ", stop - start) 

start = timeit.default_timer()
dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("DT Time : ", stop - start) 

# start = timeit.default_timer()
# svm_return = svm_fun(X_train,y_train,X_test,y_test)
# stop = timeit.default_timer()
# print("SVM Time : ", stop - start) 

gauu_nb_table.append(gauu_nb_return)
mlp_table.append(mlp_return)
knn_table.append(knn_return)
rf_table.append(rf_return)
lr_table.append(lr_return)
dt_table.append(dt_return)
# svm_table.append(svm_return)
     
# svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


Confusion Matrix NB : 
 [[ 1361    28   181]
 [   36   186   161]
 [ 3747   626 22470]]
NB Class Wise Accuracy :  [0.86687898 0.48563969 0.83708974]
NB Time :  0.14972530000000006
Confusion Matrix MLP : 
 [[  670     3   897]
 [    3    70   310]
 [  454    57 26332]]
MLP Class Wise Accuracy :  [0.42675159 0.18276762 0.98096338]
MLP Time :  22.769935799999985
Confusion Matrix KNN : 
 [[  856     2   712]
 [    6    92   285]
 [  531    86 26226]]
KNN Class Wise Accuracy :  [0.54522293 0.24020888 0.97701449]
KNN Time :  1.8145791999999972
Confusion Matrix RF : 
 [[  868     0   702]
 [    8   108   267]
 [  467   108 26268]]
RF Class Wise Accuracy :  [0.55286624 0.28198433 0.97857915]
RF Time :  3.3464486999999963
Confusion Matrix LR : 
 [[   21     6  1543]
 [    1     2   380]
 [   41    27 26775]]
LR Class Wise Accuracy :  [0.0133758  0.00522193 0.99746675]
LR Time :  0.9686672999999928
Confusion Matrix DT : 
 [[  904     1   665]
 [    8   125   250]
 [  570   162 26111]]
DT Class W

In [17]:
#taking average of all k-fold performance values
final_mean_mat = []

# final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
NB   0.834039   0.935573  0.834039       0.869813    0.538212    0.834039   
MLP  0.940131   0.930897  0.940131       0.933448    0.579387    0.940131   
KNN  0.943673   0.938340  0.943673       0.940199    0.624920    0.943673   
RF   0.946104   0.940903  0.946104       0.942852    0.642667    0.946104   
LR   0.930615   0.888648  0.930615       0.900291    0.333147    0.930615   
DT   0.942492   0.939648  0.942492       0.940931    0.644801    0.942492   

      ROC AUC  
NB   0.808755  
MLP  0.658927  
KNN  0.704855  
RF   0.716004  
LR   0.504787  
DT   0.729903

# Ridge Regression

In [20]:

X = X_orig
y =  np.array(labels_int)

ridge_data = pd.DataFrame(X)

X_train, X_test, y_train, y_test = train_test_split(
    ridge_data,y,
    test_size=0.3,
    random_state=0)
X_train.shape, X_test.shape

scaler = StandardScaler()
scaler.fit(X_train.fillna(0))

# L1 = Lasso, L2 = Ridge
sel_ = SelectFromModel(LogisticRegression(C=1, penalty='l2', solver='liblinear'))
sel_.fit(scaler.transform(X_train.fillna(0)), y_train)

sel_.get_support()

selected_feat = X_train.columns[(sel_.get_support())]
print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 19
selected features: 5
features with coefficients shrank to zero: 3


In [21]:
scaler = StandardScaler()
scaler.fit(X_train.fillna(0))

# L1 = Lasso, L2 = Ridge
sel_ = SelectFromModel(LogisticRegression(C=1, penalty='l2', solver='liblinear'))
sel_.fit(scaler.transform(X_train.fillna(0)), y_train)

sel_.get_support()

selected_feat_ridge = X_train.columns[(sel_.get_support())]
print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat_ridge)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 19
selected features: 5
features with coefficients shrank to zero: 3


In [22]:
Ridge_Regression_data = sel_.transform(ridge_data.fillna(0))

In [23]:
X = Ridge_Regression_data
y =  np.array(labels_int)


counter = 1
# print("Accuracy   Precision   Recall   F1 (weighted)   F1 (Macro)   F1 (Micro)   ROC AUC")
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []


from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=1, test_size=0.3)
sss.get_n_splits(X, y)
train_index, test_index = next(sss.split(X, y)) 

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [24]:
import timeit

start = timeit.default_timer()
gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("NB Time : ", stop - start) 

start = timeit.default_timer()
mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("MLP Time : ", stop - start) 

start = timeit.default_timer()
knn_return = knn_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("KNN Time : ", stop - start) 

start = timeit.default_timer()
rf_return = rf_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("RF Time : ", stop - start) 

start = timeit.default_timer()
lr_return = lr_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("LR Time : ", stop - start) 

start = timeit.default_timer()
dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("DT Time : ", stop - start) 

# start = timeit.default_timer()
# svm_return = svm_fun(X_train,y_train,X_test,y_test)
# stop = timeit.default_timer()
# print("SVM Time : ", stop - start) 

gauu_nb_table.append(gauu_nb_return)
mlp_table.append(mlp_return)
knn_table.append(knn_return)
rf_table.append(rf_return)
lr_table.append(lr_return)
dt_table.append(dt_return)
# svm_table.append(svm_return)
     
# svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


Confusion Matrix NB : 
 [[ 1303     0   222]
 [   44    12   342]
 [ 3905    20 22948]]
NB Class Wise Accuracy :  [0.85442623 0.03015075 0.85394262]
NB Time :  0.12953089999996337


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix MLP : 
 [[    0     0  1525]
 [    0     0   398]
 [    0     0 26873]]
MLP Class Wise Accuracy :  [0. 0. 1.]
MLP Time :  5.658490400000005
Confusion Matrix KNN : 
 [[  506     0  1019]
 [    1    16   381]
 [  538    21 26314]]
KNN Class Wise Accuracy :  [0.33180328 0.04020101 0.97919845]
KNN Time :  1.6607721999999967
Confusion Matrix RF : 
 [[  721     0   804]
 [   16     8   374]
 [  512     3 26358]]
RF Class Wise Accuracy :  [0.47278689 0.0201005  0.98083578]
RF Time :  2.214795600000002


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix LR : 
 [[    1     0  1524]
 [    0     0   398]
 [   30     0 26843]]
LR Class Wise Accuracy :  [6.55737705e-04 0.00000000e+00 9.98883638e-01]
LR Time :  0.3383728000000019
Confusion Matrix DT : 
 [[  739     0   786]
 [   16     8   374]
 [  530     5 26338]]
DT Class Wise Accuracy :  [0.48459016 0.0201005  0.98009154]
DT Time :  0.15409269999997832


In [25]:
#taking average of all k-fold performance values
final_mean_mat = []

# final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
NB   0.842582   0.929156  0.842582       0.871212    0.450419    0.842582   
MLP  0.933220   0.870899  0.933220       0.900983    0.321819    0.933220   
KNN  0.931935   0.917697  0.931935       0.921599    0.477150    0.931935   
RF   0.940651   0.933919  0.940651       0.932252    0.509277    0.940651   
LR   0.932213   0.872573  0.932213       0.900547    0.322067    0.932213   
DT   0.940582   0.932814  0.940582       0.932520    0.511244    0.940582   

      ROC AUC  
NB   0.716620  
MLP  0.500000  
KNN  0.600445  
RF   0.640279  
LR   0.499827  
DT   0.643560

# Kernel Trick

In [45]:
from sklearn.kernel_approximation import RBFSampler
X = X_orig
y =  np.array(labels_int)


from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=1, test_size=0.3)
sss.get_n_splits(X, y)
train_index, test_index = next(sss.split(X, y)) 

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

print("Train-Test Split Done")

    


#print("Random Fourier Features Starts here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

# start_time = time.time()
rbf_feature = RBFSampler(gamma=1, n_components=10)
rbf_feature.fit(X_train)
X_features_train = rbf_feature.transform(X_train)
X_features_test = rbf_feature.transform(X_test)

print("X_train rows = ",len(X_features_train),"X_train columns = ",len(X_features_train[0]))
print("X_test rows = ",len(X_features_test),"X_test columns = ",len(X_features_test[0]))

Train-Test Split Done
X_train rows =  67188 X_train columns =  10
X_test rows =  28796 X_test columns =  10


In [46]:
svm_table = []
gauu_nb_table = []
mlp_table = []
knn_table = []
rf_table = []
lr_table = []
dt_table = []


X_train = X_features_train[:]
X_test = X_features_test[:]

In [47]:
import timeit

start = timeit.default_timer()
gauu_nb_return = gaus_nb_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("NB Time : ", stop - start) 

start = timeit.default_timer()
mlp_return = mlp_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("MLP Time : ", stop - start) 

start = timeit.default_timer()
knn_return = knn_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("KNN Time : ", stop - start) 

start = timeit.default_timer()
rf_return = rf_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("RF Time : ", stop - start) 

start = timeit.default_timer()
lr_return = lr_fun(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("LR Time : ", stop - start) 

start = timeit.default_timer()
dt_return = fun_decision_tree(X_train,y_train,X_test,y_test)
stop = timeit.default_timer()
print("DT Time : ", stop - start) 

# start = timeit.default_timer()
# svm_return = svm_fun(X_train,y_train,X_test,y_test)
# stop = timeit.default_timer()
# print("SVM Time : ", stop - start) 

gauu_nb_table.append(gauu_nb_return)
mlp_table.append(mlp_return)
knn_table.append(knn_return)
rf_table.append(rf_return)
lr_table.append(lr_return)
dt_table.append(dt_return)
# svm_table.append(svm_return)
     
# svm_table_final = DataFrame(svm_table, columns=["Accuracy","Precision","Recall",
#                                                 "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
gauu_nb_table_final = DataFrame(gauu_nb_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
mlp_table_final = DataFrame(mlp_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
knn_table_final = DataFrame(knn_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
rf_table_final = DataFrame(rf_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])
lr_table_final = DataFrame(lr_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])

dt_table_final = DataFrame(dt_table, columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"])


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix NB : 
 [[    0     0  1571]
 [    0     0   359]
 [    0     0 26866]]
NB Class Wise Accuracy :  [0. 0. 1.]
NB Time :  0.1442575000000943


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix MLP : 
 [[    2     0  1569]
 [    0     0   359]
 [    5     0 26861]]
MLP Class Wise Accuracy :  [0.00127307 0.         0.99981389]
MLP Time :  24.225640500000054
Confusion Matrix KNN : 
 [[  414     4  1153]
 [   11    13   335]
 [  539    72 26255]]
KNN Class Wise Accuracy :  [0.26352642 0.0362117  0.9772575 ]
KNN Time :  3.280323699999826
Confusion Matrix RF : 
 [[  592     2   977]
 [    7    56   296]
 [  334    69 26463]]
RF Class Wise Accuracy :  [0.37683004 0.15598886 0.98499963]
RF Time :  27.878876999999875


C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix LR : 
 [[    0     0  1571]
 [    0     0   359]
 [    0     0 26866]]
LR Class Wise Accuracy :  [0. 0. 1.]
LR Time :  0.26108350000004066
Confusion Matrix DT : 
 [[  675    12   884]
 [   21    71   267]
 [ 1030   354 25482]]
DT Class Wise Accuracy :  [0.42966264 0.19777159 0.94848507]
DT Time :  1.4616814999999406


In [48]:
#taking average of all k-fold performance values
final_mean_mat = []

# final_mean_mat.append(np.transpose((list(svm_table_final.mean()))))
final_mean_mat.append(np.transpose((list(gauu_nb_table_final.mean()))))
final_mean_mat.append(np.transpose((list(mlp_table_final.mean()))))
final_mean_mat.append(np.transpose((list(knn_table_final.mean()))))
final_mean_mat.append(np.transpose((list(rf_table_final.mean()))))
final_mean_mat.append(np.transpose((list(lr_table_final.mean()))))
final_mean_mat.append(np.transpose((list(dt_table_final.mean()))))

final_avg_mat = DataFrame(final_mean_mat,columns=["Accuracy","Precision","Recall",
                                                "F1 (weighted)","F1 (Macro)","F1 (Micro)","ROC AUC"], 
                          index=["NB","MLP","KNN","RF","LR","DT"])

final_avg_mat

Accuracy  Precision    Recall  F1 (weighted)  F1 (Macro)  F1 (Micro)  \
NB   0.932977   0.870446  0.932977       0.900627    0.321775    0.932977   
MLP  0.932873   0.886083  0.932873       0.900711    0.322601    0.932873   
KNN  0.926587   0.908187  0.926587       0.915659    0.448742    0.926587   
RF   0.941485   0.930270  0.941485       0.933009    0.557534    0.941485   
LR   0.932977   0.870446  0.932977       0.900627    0.321775    0.932977   
DT   0.910821   0.916018  0.910821       0.913331    0.513490    0.910821   

      ROC AUC  
NB   0.500000  
MLP  0.500323  
KNN  0.580523  
RF   0.640535  
LR   0.500000  
DT   0.654679

# Keras Classifier

In [53]:
import time
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.preprocessing.sequence import pad_sequences


X = X_orig
y =  np.array(labels_int)


from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=1, test_size=0.9)
sss.get_n_splits(X, y)
train_index, test_index = next(sss.split(X, y)) 

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

print("Train-Test Split Done")

    
print("X_train rows = ",len(X_train),"X_train columns = ",len(X_train[0]))
print("X_test rows = ",len(X_test),"X_test columns = ",len(X_test[0]))

#print("Random Fourier Features Starts here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")

#start_time = time.time()
#rbf_feature = RBFSampler(gamma=1, n_components=500)
#rbf_feature.fit(X_train)
#X_features_train = rbf_feature.transform(X_train)
#X_features_test = rbf_feature.transform(X_test)



print("Data reduction using kernel Done@@@@@@@@@@@@@@")

unique_labels = np.unique(y)
print("unique labels = ",np.unique(y))

# https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/
aaa = (X_train.shape)
MAX_NB_WORDS = aaa[1]
EMBEDDING_DIM = 500
Memory_Units = 200
epochs = 10 # one epoch = one forward pass and one backward pass of all the training examples
batch_size = 100 # the number of training examples in one forward/backward pass. The higher the batch size, the more memory space you'll need.

#model = Sequential()
#model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=np.array(X).shape[1]))
#model.add(LSTM(Memory_Units, dropout=0.2, recurrent_dropout=0.2))
##model.add(Dense(EMBEDDING_DIM, activation='relu'))
#model.add(Dense(max(unique_labels)+1, activation='softmax'))
#model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(MAX_NB_WORDS, input_dim=np.array(X).shape[1], activation='relu'))
	model.add(Dense(max(unique_labels)+1, activation='softmax'))
	# Compile model
	model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

start_time = time.time()
estimator = KerasClassifier(build_fn=baseline_model, epochs=epochs, batch_size=batch_size, validation_split=0.1,callbacks=[EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)])

estimator.fit(X_train, y_train)
y_pred = estimator.predict(X_test)

end_time = time.time() - start_time
print("Keras Classifier Total Time in seconds =>",end_time)

Train-Test Split Done
X_train rows =  9598 X_train columns =  19
X_test rows =  86386 X_test columns =  19
Data reduction using kernel Done@@@@@@@@@@@@@@
unique labels =  [0 1 2]
Epoch 1/10
87/87 [==============================] - 10s 5ms/step - loss: 10762.3258 - accuracy: 0.0796 - val_loss: 229.0894 - val_accuracy: 0.9312
Epoch 2/10
87/87 [==============================] - 0s 1ms/step - loss: 193.7614 - accuracy: 0.9315 - val_loss: 19.5105 - val_accuracy: 0.9271
Epoch 3/10
87/87 [==============================] - 0s 2ms/step - loss: 9.2148 - accuracy: 0.9043 - val_loss: 7.6271 - val_accuracy: 0.9292
Epoch 4/10
87/87 [==============================] - 0s 1ms/step - loss: 6.1796 - accuracy: 0.9118 - val_loss: 8.0393 - val_accuracy: 0.9135
Epoch 5/10
87/87 [==============================] - 0s 1ms/step - loss: 5.9936 - accuracy: 0.9124 - val_loss: 6.3682 - val_accuracy: 0.8927
Epoch 6/10
87/87 [==============================] - 0s 1ms/step - loss: 7.3207 - accuracy: 0.9022 - val_loss: 6

C:\Users\sali85\Anaconda3\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Keras Classifier Total Time in seconds => 11.582735776901245


In [54]:
RC_acc = metrics.accuracy_score(y_test, y_pred)
RC_prec = metrics.precision_score(y_test, y_pred,average='weighted')
RC_recall = metrics.recall_score(y_test, y_pred,average='weighted')
RC_f1_weighted = metrics.f1_score(y_test, y_pred,average='weighted')
RC_f1_macro = metrics.f1_score(y_test, y_pred,average='macro')
RC_f1_micro = metrics.f1_score(y_test, y_pred,average='micro')
confuse = confusion_matrix(y_test, y_pred)
y_prob = y_pred
macro_roc_auc_ovo = roc_auc_score_multiclass(y_test, y_prob, average='macro')

check = [RC_acc,RC_prec,RC_recall,RC_f1_weighted,RC_f1_macro,RC_f1_micro,macro_roc_auc_ovo[1]]

print("Final score",check)

C:\Users\sali85\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Final score [0.9314124973954113, 0.8677791685333658, 0.9314124973954113, 0.8984705497000357, 0.3214961411752484, 0.9314124973954113, 0.49995063894183284]


In [7]:
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.models import Sequential

from keras_fsl.models.encoders import BasicCNN
from keras_fsl.layers import GramMatrix
from keras_fsl.losses.gram_matrix_losses import BinaryCrossentropy
from keras_fsl.metrics.gram_matrix_metrics import classification_accuracy, min_eigenvalue
from keras_fsl.utils.tensors import get_dummies




In [14]:
X = X_orig
y =  np.array(labels_int)


from sklearn.model_selection import ShuffleSplit # or StratifiedShuffleSplit
sss = ShuffleSplit(n_splits=1, test_size=0.9)
sss.get_n_splits(X, y)
train_index, test_index = next(sss.split(X, y)) 

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [17]:
#%% Get data
train_dataset, val_dataset, test_dataset = [
    dataset.shuffle(1024).batch(64).map(lambda x, y: (tf.image.convert_image_dtype(x, tf.float32), get_dummies(y)[0]))
    for dataset in tfds.load(name="omniglot", split=["train[:90%]", "train[90%:]", "test"], as_supervised=True)
]
input_shape = next(tfds.as_numpy(train_dataset.take(1)))[0].shape[1:]  # first shape is batch_size

ExtractError: Error while extracting C:\Users\sali85\tensorflow_datasets\downloads\brend_omnig_raw_maste_pytho_image_evalubGVoN2jrejt9ilVCYaN4mqEREeA_1qeml3UWyWtc3N8.zip to C:\Users\sali85\tensorflow_datasets\downloads\extracted\ZIP.brend_omnig_raw_maste_pytho_image_evalubGVoN2jrejt9ilVCYaN4mqEREeA_1qeml3UWyWtc3N8.zip (file: images_evaluation\Old_Church_Slavonic_(Cyrillic)\character01\1389_01.png) : Failed to create a directory: C:\Users\sali85\tensorflow_datasets\downloads\extracted\ZIP.brend_omnig_raw_maste_pytho_image_evalubGVoN2jrejt9ilVCYaN4mqEREeA_1qeml3UWyWtc3N8.zip.incomplete_6e3fc6c631ac4049a5524c004f74d4bf\images_evaluation/Old_Church_Slavonic_(Cyrillic)/character01; No such file or directory
On windows, path lengths greater than 260 characters may result in an error. See the doc to remove the limiration: https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

In [20]:


#%% Training
encoder = BasicCNN(input_shape=len(X_train))
support_layer = GramMatrix(kernel="DenseSigmoid")
model = Sequential([encoder, support_layer])
model.compile(optimizer="Adam", loss=BinaryCrossentropy(), metrics=[classification_accuracy(), min_eigenvalue])
model.fit(X_train, validation_data=val_dataset, epochs=5)

TypeError: 'int' object is not iterable

In [22]:
# !pip install git+https://github.com/sicara/easy-few-shot-learning.git



In [27]:
from easyfsl.methods import PrototypicalNetworks
from torch import nn
from torch.optim import Adam
from torchvision.models import resnet18

convolutional_network = resnet18(pretrained=False)
convolutional_network.fc = nn.Flatten()
model = PrototypicalNetworks(convolutional_network)

# model = Sequential()

optimizer = Adam(params=model.parameters())

model.fit(X_train[0], optimizer)

Meta-Training:   0%|                                                                            | 0/19 [00:00<?, ?it/s]


TypeError: cannot unpack non-iterable numpy.int32 object